#!/bin/bash

uv venv
source .venv/bin/activate
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    sudo apt-get update && sudo apt-get install -y swig
else
    brew install swig
fi
uv pip install -r requirements.txt
